#!/bin/sh

set -e

echo "Building the example site..."

# copy the sass components from materialize npm package
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp -r $DIR/../node_modules/materialize-css/sass/components $DIR/../_sass

bundle exec jekyll build
